<?php

namespace Annonces\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function myFindAll(){
        // Méthode 1 : en passant par l'EntityManager
        $queryBuilder = $this->createNativeNamedQuery('c');
        $query = $queryBuilder->getQuery();
        $results = $query->getResult();
        return $results;
    }

    public function getCategories($page, $nbPerPage){
        $query = $this->createQueryBuilder('c')->getQuery();
        $query ->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);
        return new Paginator($query, true);
    }

    public function getCategory($nbPerPage){
        $queryBuilder = $this->createQueryBuilder('c');
        $query = $queryBuilder->getQuery();
        $query->setMaxResults($nbPerPage);
        $result = $query->getResult();
        return $result;
    }


}
