# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
          #Symfony\Component\Security\Core\User\User: plaintext
        #Symfony\Component\Security\Core\User\User:
        Annonces\BackendBundle\Entity\User:
           algorithm: bcrypt
           cost: 12
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        main:
            entity: { class: Annonces\BackendBundle\Entity\User, property: email }


    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /connexion
                check_path:  /login_check
            logout:
                path:   /logout
                target: /connexion

    access_control:
            - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/private, roles: ROLE_ADMIN }
            - { path: ^/admin/dashboard, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
            - { path: ^/admin/*, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
